### ISSUE TITLE
QR CODE GENERATOR

### ISSUE THREAD

**Issue by Nirvik07** [SamarthTech/Pyhton-GUI-Projects#16]
# Describe the project you want to add with tech stack
Making a QR Code Generator using CustomTkinter

# Expected behavior
A QR code generator is a tool or software that allows you to create Quick Response (QR) codes. QR codes are two-dimensional barcodes that can store various types of information, such as URLs, text, contact information, or other data. These codes are designed to be quickly scanned and read by smartphones and other QR code readers.

**Comment by Nirvik07** [comment]
Please assign me this isssue.

**Comment by codingniket** [comment]
Done
